server:
  port: 9008
spring:
  application:  
    name: how-user #指定服务名
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://101.201.142.43:3306/how_user?characterEncoding=utf-8

    username: root
    password: root
  jpa: 
    database: MySQL
    show-sql: true
  rabbitmq:
    host: 101.201.142.43

  redis:
    host: 101.201.142.43

jwt:
  config:
    key: howblog  #注意这个key不能太短
    ttl: 360000