server:
  port: 9006

spring:
  application:
    name: how-spit #指定服务名
  data:
    mongodb:
      host: 101.201.142.43
      database: spitdb

  redis:
    host: 101.201.142.43

  # nacos服务地址
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848