server: 
  port: 9004
spring: 
  application:  
    name: how-article #指定服务名
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://101.201.142.43:3306/how_article?characterEncoding=utf-8
    username: root
    password: root
  jpa: 
    database: MySQL
    show-sql: true

  # nacos服务地址
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

  redis:
    host: 101.201.142.43
  data:
    mongodb:
      host: 101.201.142.43
      database: commentdb
