version: '3'
services:
  #消息服务
  how_sms:
    image: registry.cn-beijing.aliyuncs.com/liushao-repository/how_sms:latest
    container_name: how_sms
    restart: always
    ports:
      - 9009:9009
    networks:
      - how
    environment:
      - COMPOSE_PROJECT_NAME=how_sms
    volumes:
      - ../log/:/logs/
networks:
  how:
    external: true