version: '3'
services:
  #网关服务
  how_gateway_web:
    image: registry.cn-beijing.aliyuncs.com/liushao-repository/how_gateway_web:latest
    container_name: how_gateway_web
    restart: always
    ports:
      - 9005:9005
    networks:
      - how
    environment:
      - COMPOSE_PROJECT_NAME=how_gateway_web
    volumes:
      - ../log/:/logs/
networks:
  how:
    external: true