version: '3'
services:
  #活动服务
  how_gathering:
    image: registry.cn-beijing.aliyuncs.com/liushao-repository/how_gathering:latest
    container_name: how_gathering
    restart: always
    ports:
      - 9005:9005
    networks:
      - how
    environment:
      - COMPOSE_PROJECT_NAME=how_gathering
    volumes:
      - ../log/:/logs/
networks:
  how:
    external: true