version: '3'
services:
  #文章服务
  mogu_admin:
    image: registry.cn-beijing.aliyuncs.com/liushao-repository/how_article:latest
    container_name: how_article
    restart: always
    ports:
      - 9004:9004
    networks:
      - mogu
    environment:
      - COMPOSE_PROJECT_NAME=how_article
    volumes:
      - ../log/:/logs/
      - ../config/how_article/:/config/
networks:
  how:
    external: true