server:
  port: 9003
spring:
  application:  
    name: how-user #指定服务名
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://222.222.222.222:3306/how_user?characterEncoding=utf-8
    username: root
    password: root
  jpa: 
    database: MySQL
    show-sql: true
  rabbitmq:
    host: 111.111.111.111
    username: guest
    password: guest
  redis:
    host: 222.222.222.222
  # nacos服务地址
  cloud:
    nacos:
      discovery:
        server-addr: 222.222.222.222:8848
        namespace: dev
jwt:
  config:
    key: xxxxxxxxxxxx  #注意这个key不能太短
    ttl: 360000