server:
  port: 9001
spring:
  application:
    name: how-article #指定服务名
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://222.222.222.222:3306/how_article?characterEncoding=utf-8
    username: root
    password: root
  jpa:
    database: MySQL
    show-sql: true

  # nacos服务地址
  cloud:
    nacos:
      discovery:
        server-addr: 222.222.222.222:8848
        namespace: dev

  redis:
    host: 222.222.222.222
  data:
    mongodb:
      host: 111.111.111.111
      database: commentdb

#开启熔断机制
feign:
  hystrix:
    enabled: true

jwt:
  config:
    key: xxxxxxxxxxx  #注意这个key不能太短
    ttl: 360000
    
# 111.111.111.111  我的阿里云服务器地址