server:
  port: 9004
spring:
  application:
    name: how-sms #指定服务名
  rabbitmq:
    host: 111.111.111.111
    username: guest
    password: guest

  # nacos服务地址
  cloud:
    nacos:
      discovery:
        server-addr: 222.222.222.222:8848
        namespace: dev

aliyun:
  sms:
    template_code: xxxxxxxxx
    sign_name: xxxxxxxxxxx
    accessKeyId: xxxxxxxxxxxx
    accessKeySecret: xxxxxxxxxxxxxxxxx